### ISSUE TITLE
Word order issues

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/matrix-react-sdk#18]
Some strings are split and for some languages in the wrong order like ``Drop here to [xxxxxxx]``. In German the second part (here in brackets) needs to be first

**Comment by dtygel** [comment]
The only way to solve this is allowing variables inside the strings. Something like `{ counterpart.translate("Hi, %s! Drop here to %s", [username,verb]) }`

**Comment by MTRNord** [comment]
weblate should also be a able to do that. otherwise I would just add a small text about it in the new doc I added. I later will add screenshots to weblate so they will see what changes where and which string does which translation

**Comment by dtygel** [comment]
Solved. Look at that: https://github.com/MTRNord/riot-web/pull/14

**Comment by MTRNord** [comment]
Solved by dtygel
