### ISSUE TITLE
rework counterpart structure

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/matrix-react-sdk#9]
use a instance which can be accesed by both sides and Move all strings to react-sdk.

**Comment by dtygel** [comment]
You mean moving strings from riot-web to react-sdk? In Android, the translation strings are separated (those in riot-android and those in matrix-android-sdk), which seem to me more logic, to maintain the independence between both platforms...

**Comment by MTRNord** [comment]
@dtygel actually this idea came from someone in the riot-dev chat :) to keep it more simple to handle. because it will be a singelton be made for the counterpart thingy to not have the dispatching between riot-web and react-sdk but I will see how I will manage that. currently they will be kept seperated between both repos

**Comment by MTRNord** [comment]
All files are stioll in the same repo. but loaded over a request at runtime. at compile time they will be merged together.
